#!/bin/sh
set -e
dir="`git rev-parse --show-toplevel`"

trap 'rm -f "$dir/$$.tags"' EXIT
ctags --exclude=.git --exclude=log -f "$dir/$$.tags" -R "$dir"
mv "$dir/$$.tags" "$dir/tags"

if [ -e "$dir/GTAGS" ]; then
    global -u
else
    GTAGSROOT="${dir}" gtags
fi
