*
+
-
->char-set
->string
/
<
<=
=
>
>=
@
_exit
abandoned-mutex-exception?
abort
abs
absolute-pathname?
acos
add1
address->pointer
align-to-word
alist->hash-table
alist-cons
alist-copy
alist-delete
alist-delete!
alist-ref
alist-update!
allocate
always?
and
and-let*
angle
any
any?
append
append!
append-map
append-map!
append-reverse
append-reverse!
apply
apropos#apropos
apropos#apropos-information-list
apropos#apropos-list
argc+argv
argv
arithmetic-shift
asin
assert
assoc
assq
assv
atan
atom?
begin
begin-for-syntax
binary-search
bit-set?
bitwise-and
bitwise-ior
bitwise-not
bitwise-xor
blob->f32vector
blob->f32vector/shared
blob->f64vector
blob->f64vector/shared
blob->s16vector
blob->s16vector/shared
blob->s32vector
blob->s32vector/shared
blob->s8vector
blob->s8vector/shared
blob->string
blob->u16vector
blob->u16vector/shared
blob->u32vector
blob->u32vector/shared
blob->u8vector
blob->u8vector/shared
blob-size
blob=?
blob?
block-device?
block-ref
block-set!
boolean?
break
break!
build-platform
butlast
c-runtime
caaaar
caaadr
caaar
caadar
caaddr
caadr
caar
cadaar
cadadr
cadar
caddar
cadddr
caddr
cadr
call-with-current-continuation
call-with-input-file
call-with-input-pipe
call-with-input-string
call-with-output-file
call-with-output-pipe
call-with-output-string
call-with-values
call/cc
car
car+cdr
case
case-lambda
case-sensitive
cdaaar
cdaadr
cdaar
cdadar
cdaddr
cdadr
cdar
cddaar
cddadr
cddar
cdddar
cddddr
cdddr
cddr
cdr
ceiling
change-directory
change-file-mode
change-file-owner
char->integer
char-alphabetic?
char-ci<=?
char-ci<?
char-ci=?
char-ci>=?
char-ci>?
char-downcase
char-lower-case?
char-name
char-numeric?
char-ready?
char-set
char-set->list
char-set->string
char-set-adjoin
char-set-adjoin!
char-set-any
char-set-complement
char-set-complement!
char-set-contains?
char-set-copy
char-set-count
char-set-cursor
char-set-cursor-next
char-set-delete
char-set-delete!
char-set-diff+intersection
char-set-diff+intersection!
char-set-difference
char-set-difference!
char-set-every
char-set-filter
char-set-filter!
char-set-fold
char-set-for-each
char-set-hash
char-set-intersection
char-set-intersection!
char-set-map
char-set-ref
char-set-size
char-set-unfold
char-set-unfold!
char-set-union
char-set-union!
char-set-xor
char-set-xor!
char-set:ascii
char-set:blank
char-set:digit
char-set:empty
char-set:full
char-set:graphic
char-set:hex-digit
char-set:iso-control
char-set:letter
char-set:letter+digit
char-set:lower-case
char-set:printing
char-set:punctuation
char-set:s
char-set:symbol
char-set:title-case
char-set:upper-case
char-set:whitespace
char-set<=
char-set=
char-set?
char-upcase
char-upper-case?
char-whitespace?
char<=?
char<?
char=?
char>=?
char>?
char?
character-device?
check-substring-spec
chicken-home
chicken-version
chop
circular-list
circular-list?
close-input-pipe
close-input-port
close-output-pipe
close-output-port
command-line-arguments
compile-file
compile-file-options
complement
complex?
compose
compress
conc
concatenate
concatenate!
cond
cond-expand
condition->list
condition-case
condition-predicate
condition-property-accessor
condition-variable-broadcast!
condition-variable-name
condition-variable-signal!
condition-variable-specific
condition-variable-specific-set!
condition-variable?
condition?
conjoin
cons
cons*
constantly
continuation-capture
continuation-graft
continuation-return
continuation?
copy-port
copy-read-table
cos
count
cpu-time
create-directory
create-fifo
create-pipe
create-session
create-symbolic-link
create-temporary-directory
create-temporary-file
current-directory
current-effective-group-id
current-effective-user-id
current-effective-user-name
current-error-port
current-exception-handler
current-gc-milliseconds
current-group-id
current-input-port
current-milliseconds
current-output-port
current-process-id
current-read-table
current-seconds
current-thread
current-time
current-user-id
current-user-name
cut
cute
declare
decompose-directory
decompose-pathname
define
define-compiler-syntax
define-constant
define-for-syntax
define-inline
define-reader-ctor
define-record
define-record-printer
define-record-type
define-syntax
define-values
delay
delete
delete!
delete-directory
delete-duplicates
delete-duplicates!
delete-file
delete-file*
denominator
directory
directory-exists?
directory-null?
directory?
disjoin
display
do
dotted-list?
drop
drop-right
drop-right!
drop-while
duplicate-fileno
dynamic-load-libraries
dynamic-wind
each
editor-command
eighth
enable-warnings
end-of-char-set?
ensure
eof-object?
eq?
eq?-hash
equal=?
equal?
equal?-hash
eqv?
eqv?-hash
er-macro-transformer
errno
errno/2big
errno/acces
errno/again
errno/badf
errno/busy
errno/child
errno/deadlk
errno/dom
errno/exist
errno/fault
errno/fbig
errno/ilseq
errno/intr
errno/inval
errno/io
errno/isdir
errno/mfile
errno/mlink
errno/nametoolong
errno/nfile
errno/nodev
errno/noent
errno/noexec
errno/nolck
errno/nomem
errno/nospc
errno/nosys
errno/notdir
errno/notempty
errno/notty
errno/nxio
errno/perm
errno/pipe
errno/range
errno/rofs
errno/spipe
errno/srch
errno/wouldblock
errno/xdev
error
eval
eval-handler
eval-when
even?
every
exact->inexact
exact?
exit
exit-handler
exp
expand
export
expt
extend-procedure
extended-procedure?
extension-information
f32vector
f32vector->blob
f32vector->blob/shared
f32vector->list
f32vector-length
f32vector-ref
f32vector-set!
f32vector?
f64vector
f64vector->blob
f64vector->blob/shared
f64vector->list
f64vector-length
f64vector-ref
f64vector-set!
f64vector?
fcntl/dupfd
fcntl/getfd
fcntl/getfl
fcntl/setfd
fcntl/setfl
feature?
features
fifo?
fifth
file-access-time
file-change-time
file-close
file-control
file-copy
file-creation-mode
file-execute-access?
file-exists?
file-link
file-lock
file-lock/blocking
file-mkstemp
file-modification-time
file-move
file-open
file-owner
file-permissions
file-position
file-read
file-read-access?
file-select
file-size
file-stat
file-test-lock
file-truncate
file-type
file-unlock
file-write
file-write-access?
fileno/stderr
fileno/stdin
fileno/stdout
filter
filter!
filter-map
find
find-files
find-tail
finite?
first
fixnum-bits
fixnum-precision
fixnum?
flatten
flip
flonum-decimal-precision
flonum-epsilon
flonum-maximum-decimal-exponent
flonum-maximum-exponent
flonum-minimum-decimal-exponent
flonum-minimum-exponent
flonum-precision
flonum-print-precision
flonum-radix
flonum?
floor
fluid-let
flush-output
fold
fold-right
for-each
force
force-finalizers
format
fourth
fp*
fp+
fp-
fp/
fp<
fp<=
fp=
fp>
fp>=
fpabs
fpacos
fpasin
fpatan
fpatan2
fpceiling
fpcos
fpexp
fpexpt
fpfloor
fpinteger?
fplog
fpmax
fpmin
fpneg
fprintf
fpround
fpsin
fpsqrt
fptan
fptruncate
free
fx*
fx*?
fx+
fx+?
fx-
fx-?
fx/
fx/?
fx<
fx<=
fx=
fx>
fx>=
fxand
fxeven?
fxior
fxmax
fxmin
fxmod
fxneg
fxnot
fxodd?
fxshl
fxshr
fxxor
gc
gcd
gensym
get
get-call-chain
get-condition-property
get-environment-variable
get-environment-variables
get-groups
get-host-name
get-keyword
get-line-number
get-output-string
get-properties
getter-with-setter
glob
group-information
handle-exceptions
hash
hash-by-identity
hash-table->alist
hash-table-clear!
hash-table-copy
hash-table-delete!
hash-table-equivalence-function
hash-table-exists?
hash-table-fold
hash-table-for-each
hash-table-has-initial?
hash-table-hash-function
hash-table-initial
hash-table-keys
hash-table-map
hash-table-max-load
hash-table-merge
hash-table-merge!
hash-table-min-load
hash-table-ref
hash-table-ref/default
hash-table-remove!
hash-table-resize!
hash-table-set!
hash-table-size
hash-table-update!
hash-table-update!/default
hash-table-values
hash-table-walk
hash-table-weak-keys
hash-table-weak-values
hash-table?
identity
if
imag-part
implicit-exit-handler
import
import-for-syntax
include
inexact->exact
inexact?
initialize-groups
input-port?
integer->char
integer?
interaction-environment
intersperse
iota
ir-macro-transformer
irregex
irregex-apply-match
irregex-dfa
irregex-dfa/extract
irregex-dfa/search
irregex-extract
irregex-flags
irregex-fold
irregex-fold/chunked
irregex-lengths
irregex-match
irregex-match-data?
irregex-match-end-chunk
irregex-match-end-index
irregex-match-names
irregex-match-num-submatches
irregex-match-start-chunk
irregex-match-start-index
irregex-match-subchunk
irregex-match-substring
irregex-match-valid-index?
irregex-match/chunked
irregex-match?
irregex-names
irregex-new-matches
irregex-nfa
irregex-num-submatches
irregex-opt
irregex-quote
irregex-replace
irregex-replace/all
irregex-reset-matches!
irregex-search
irregex-search/chunked
irregex-search/matches
irregex-split
irregex?
join
join-timeout-exception?
keyword->string
keyword-hash
keyword-style
keyword?
kmp-step
lambda
last
last-pair
lcm
length
length+
let
let*
let*-values
let-compiler-syntax
let-optionals
let-optionals*
let-syntax
let-values
letrec
letrec-syntax
letrec-values
list
list->char-set
list->char-set!
list->f32vector
list->f64vector
list->queue
list->s16vector
list->s32vector
list->s8vector
list->string
list->u16vector
list->u32vector
list->u8vector
list->vector
list-copy
list-index
list-of?
list-ref
list-tabulate
list-tail
list=
list?
load
load-library
load-noisily
load-relative
load-verbose
local-time->seconds
local-timezone-abbreviation
locative->object
locative-ref
locative-set!
locative?
log
lookup-table#alist->dict
lookup-table#check-dict
lookup-table#dict->alist
lookup-table#dict-count
lookup-table#dict-delete!
lookup-table#dict-equivalence-function
lookup-table#dict-exists?
lookup-table#dict-for-each
lookup-table#dict-indempotent-ref!
lookup-table#dict-keys
lookup-table#dict-merge!
lookup-table#dict-print
lookup-table#dict-ref
lookup-table#dict-safe-mode
lookup-table#dict-search
lookup-table#dict-set!
lookup-table#dict-update!
lookup-table#dict-update-dict!
lookup-table#dict-update-list!
lookup-table#dict-values
lookup-table#dict?
lookup-table#error-dict
lookup-table#make-dict
lset-adjoin
lset-diff+intersection
lset-diff+intersection!
lset-difference
lset-difference!
lset-intersection
lset-intersection!
lset-union
lset-union!
lset-xor
lset-xor!
lset<=
lset=
machine-byte-order
machine-type
magnitude
make-absolute-pathname
make-blob
make-broadcast-port
make-char-set
make-composite-condition
make-concatenated-port
make-condition-variable
make-er/ir-transformer
make-f32vector
make-f64vector
make-hash-table
make-input-port
make-irregex-chunker
make-kmp-restart-vector
make-list
make-locative
make-mutex
make-output-port
make-parameter
make-pathname
make-pointer-vector
make-property-condition
make-queue
make-record-instance
make-s16vector
make-s32vector
make-s8vector
make-string
make-thread
make-u16vector
make-u32vector
make-u8vector
make-vector
make-weak-locative
map
map!
map-file-to-memory
map-in-order
map/anonymous
map/file
map/fixed
map/private
map/shared
max
maximum-flonum
maybe-string->sre
member
memoized-string#make-string*
memory-mapped-file-pointer
memory-mapped-file?
memory-statistics
memq
memv
merge
merge!
min
minimum-flonum
module
module-undefined-list
modulo
most-negative-fixnum
most-positive-fixnum
move-memory!
mutate-procedure
mutex-lock!
mutex-name
mutex-specific
mutex-specific-set!
mutex-state
mutex-unlock!
mutex?
negative?
never?
newline
ninth
none?
normalize-pathname
not
not-pair?
nth-value
null-environment
null-list?
null-pointer
null-pointer?
null?
number->string
number-hash
number-of-bytes
number-of-slots
number?
numerator
o
object->pointer
object-become!
object-copy
object-evict
object-evict-to-location
object-evicted?
object-release
object-size
object-uid-hash
object-unevict
odd?
on-exit
open-input-file
open-input-file*
open-input-pipe
open-input-string
open-output-file
open-output-file*
open-output-pipe
open-output-string
open/append
open/binary
open/creat
open/excl
open/fsync
open/noctty
open/nonblock
open/rdonly
open/rdwr
open/read
open/sync
open/text
open/trunc
open/write
open/wronly
optional
or
output-port?
pair-fold
pair-fold-right
pair-for-each
pair?
parameterize
parent-process-id
parentheses-synonyms
partition
partition!
pathname-directory
pathname-extension
pathname-file
pathname-replace-directory
pathname-replace-extension
pathname-replace-file
pathname-strip-directory
pathname-strip-extension
peek-char
perm/irgrp
perm/iroth
perm/irusr
perm/irwxg
perm/irwxo
perm/irwxu
perm/isgid
perm/isuid
perm/isvtx
perm/iwgrp
perm/iwoth
perm/iwusr
perm/ixgrp
perm/ixoth
perm/ixusr
pipe/buf
pointer+
pointer->address
pointer->object
pointer-f32-ref
pointer-f32-set!
pointer-f64-ref
pointer-f64-set!
pointer-like?
pointer-offset
pointer-s16-ref
pointer-s16-set!
pointer-s32-ref
pointer-s32-set!
pointer-s8-ref
pointer-s8-set!
pointer-tag
pointer-u16-ref
pointer-u16-set!
pointer-u32-ref
pointer-u32-set!
pointer-u8-ref
pointer-u8-set!
pointer-vector
pointer-vector-fill!
pointer-vector-length
pointer-vector-ref
pointer-vector-set!
pointer-vector?
pointer=?
pointer?
port->fileno
port-closed?
port-fold
port-for-each
port-map
port-name
port-position
port?
positive?
pp
pretty-print
pretty-print-width
print
print*
print-call-chain
print-error-message
printf
procedure-data
procedure-information
procedure?
process
process*
process-execute
process-fork
process-group-id
process-run
process-signal
process-wait
program-name
promise?
proper-list?
prot/exec
prot/none
prot/read
prot/write
provide
provided?
put!
qs
quasiquote
queue->list
queue-add!
queue-empty?
queue-first
queue-last
queue-push-back!
queue-push-back-list!
queue-remove!
queue?
quote
quotient
raise
random
randomize
rassoc
rational?
read
read-all
read-buffered
read-byte
read-char
read-file
read-line
read-lines
read-string
read-string!
read-symbolic-link
read-token
read-u8vector
read-u8vector!
real-part
real?
rec
receive
record->vector
record-instance-length
record-instance-slot
record-instance-slot-set!
record-instance-type
record-instance?
reduce
reduce-right
reexport
regex#glob->regexp
regex#grep
regex#regexp
regex#regexp-escape
regex#regexp?
regex#string-match
regex#string-match-positions
regex#string-search
regex#string-search-positions
regex#string-split-fields
regex#string-substitute
regex#string-substitute*
register-feature!
regular-file?
release-number-vector
remainder
remove
remove!
remprop!
rename-file
repl
repl-prompt
repository-path
require
require-extension
require-library
reset
reset-handler
return-to-host
reverse
reverse!
reverse-list->string
reverse-string-append
round
s16vector
s16vector->blob
s16vector->blob/shared
s16vector->list
s16vector-length
s16vector-ref
s16vector-set!
s16vector?
s32vector
s32vector->blob
s32vector->blob/shared
s32vector->list
s32vector-length
s32vector-ref
s32vector-set!
s32vector?
s8vector
s8vector->blob
s8vector->blob/shared
s8vector->list
s8vector-length
s8vector-ref
s8vector-set!
s8vector?
scan-input-lines
scheme-report-environment
second
seconds->local-time
seconds->string
seconds->time
seconds->utc-time
seek/cur
seek/end
seek/set
select
set!
set!-values
set-alarm!
set-buffering-mode!
set-car!
set-cdr!
set-describer!
set-dynamic-load-mode!
set-file-position!
set-finalizer!
set-gc-report!
set-groups!
set-module-undefined-list!
set-parameterized-read-syntax!
set-port-name!
set-procedure-data!
set-read-syntax!
set-root-directory!
set-sharp-read-syntax!
set-signal-handler!
set-signal-mask!
setenv
setter
seventh
shuffle
signal
signal-handler
signal-mask
signal-mask!
signal-masked?
signal-unmask!
signal/abrt
signal/alrm
signal/chld
signal/cont
signal/fpe
signal/hup
signal/ill
signal/int
signal/io
signal/kill
signal/pipe
signal/prof
signal/quit
signal/segv
signal/stop
signal/term
signal/trap
signal/tstp
signal/urg
signal/usr1
signal/usr2
signal/vtalrm
signal/winch
signal/xcpu
signal/xfsz
signals-list
signum
sin
sixth
sleep
socket?
software-type
software-version
sort
sort!
sorted?
span
span!
split-at
split-at!
sprintf
sqrt
sre->irregex
sre->string
string
string->blob
string->char-set
string->char-set!
string->irregex
string->keyword
string->list
string->number
string->sre
string->symbol
string->time
string->uninterned-symbol
string-any
string-append
string-append/shared
string-chomp
string-chop
string-ci-hash
string-ci<
string-ci<=
string-ci<=?
string-ci<>
string-ci<?
string-ci=
string-ci=?
string-ci>
string-ci>=
string-ci>=?
string-ci>?
string-compare
string-compare-ci
string-compare3
string-compare3-ci
string-concatenate
string-concatenate-reverse
string-concatenate-reverse/shared
string-concatenate/shared
string-contains
string-contains-ci
string-copy
string-copy!
string-count
string-delete
string-downcase
string-downcase!
string-drop
string-drop-right
string-every
string-fill!
string-filter
string-fold
string-fold-right
string-for-each
string-for-each-index
string-hash
string-hash-ci
string-index
string-index-right
string-intersperse
string-join
string-kmp-partial-search
string-length
string-map
string-map!
string-null?
string-pad
string-pad-right
string-parse-final-start+end
string-parse-start+end
string-prefix-ci?
string-prefix-length
string-prefix-length-ci
string-prefix?
string-ref
string-replace
string-reverse
string-reverse!
string-set!
string-skip
string-skip-right
string-split
string-suffix-ci?
string-suffix-length
string-suffix-length-ci
string-suffix?
string-tabulate
string-take
string-take-right
string-titlecase
string-titlecase!
string-tokenize
string-translate
string-translate*
string-trim
string-trim-both
string-trim-right
string-unfold
string-unfold-right
string-upcase
string-upcase!
string-xcopy!
string<
string<=
string<=?
string<>
string<?
string=
string=?
string>
string>=
string>=?
string>?
string?
strip-syntax
sub1
subf32vector
subf64vector
subs16vector
subs32vector
subs8vector
substring
substring-ci=?
substring-index
substring-index-ci
substring-spec-ok?
substring/shared
substring=?
subu16vector
subu32vector
subu8vector
symbol->string
symbol-append
symbol-escape
symbol-hash
symbol-plist
symbol-utils#interned-symbol?
symbol-utils#make-qualified-symbol
symbol-utils#make-qualified-uninterned-symbol
symbol-utils#max-symbol-printname-length
symbol-utils#qualified-symbol?
symbol-utils#symbol->keyword
symbol-utils#symbol->qualified-string
symbol-utils#symbol-printname-details
symbol-utils#symbol-printname-length
symbol-utils#symbol-printname<?
symbol-utils#symbol-printname=?
symbol-utils#unspecified-value
symbol?
symbolic-link?
symbolize
syntax
syntax-error
syntax-rules
system
system*
system-information
tag-pointer
tagged-pointer?
tail?
take
take!
take-right
take-while
take-while!
tan
tcp-abandon-port
tcp-accept
tcp-accept-ready?
tcp-accept-timeout
tcp-addresses
tcp-buffer-size
tcp-close
tcp-connect
tcp-connect-timeout
tcp-listen
tcp-listener-fileno
tcp-listener-port
tcp-listener?
tcp-port-numbers
tcp-read-timeout
tcp-write-timeout
tenth
terminal-name
terminal-port?
terminal-size
terminated-thread-exception?
third
thread-join!
thread-name
thread-quantum
thread-quantum-set!
thread-resume!
thread-signal!
thread-sleep!
thread-specific
thread-specific-set!
thread-start!
thread-state
thread-suspend!
thread-terminate!
thread-wait-for-i/o!
thread-yield!
thread?
time
time->seconds
time->string
time?
toplevel-command
topological-sort
truncate
type-checks#alist?
type-checks#check-alist
type-checks#check-argument-count
type-checks#check-blob
type-checks#check-boolean
type-checks#check-bound-value
type-checks#check-cardinal-fixnum
type-checks#check-cardinal-integer
type-checks#check-cardinal-number
type-checks#check-char
type-checks#check-closed-interval
type-checks#check-closure
type-checks#check-complex
type-checks#check-defined-value
type-checks#check-exact
type-checks#check-fixnum
type-checks#check-flonum
type-checks#check-half-closed-interval
type-checks#check-half-open-interval
type-checks#check-inexact
type-checks#check-input-port
type-checks#check-integer
type-checks#check-keyword
type-checks#check-list
type-checks#check-minimum-argument-count
type-checks#check-natural-fixnum
type-checks#check-natural-integer
type-checks#check-natural-number
type-checks#check-number
type-checks#check-open-interval
type-checks#check-output-port
type-checks#check-pair
type-checks#check-positive-fixnum
type-checks#check-positive-integer
type-checks#check-positive-number
type-checks#check-procedure
type-checks#check-rational
type-checks#check-real
type-checks#check-record
type-checks#check-record-type
type-checks#check-string
type-checks#check-structure
type-checks#check-symbol
type-checks#check-vector
type-checks#plist?
type-errors#error-alist
type-errors#error-argument-count
type-errors#error-argument-type
type-errors#error-blob
type-errors#error-boolean
type-errors#error-bound-value
type-errors#error-cardinal-fixnum
type-errors#error-cardinal-integer
type-errors#error-cardinal-number
type-errors#error-char
type-errors#error-closed-interval
type-errors#error-closure
type-errors#error-complex
type-errors#error-defined-value
type-errors#error-exact
type-errors#error-fixnum
type-errors#error-flonum
type-errors#error-half-closed-interval
type-errors#error-half-open-interval
type-errors#error-inexact
type-errors#error-input-port
type-errors#error-integer
type-errors#error-interval
type-errors#error-keyword
type-errors#error-list
type-errors#error-minimum-argument-count
type-errors#error-natural-fixnum
type-errors#error-natural-integer
type-errors#error-natural-number
type-errors#error-number
type-errors#error-open-interval
type-errors#error-output-port
type-errors#error-pair
type-errors#error-plist
type-errors#error-positive-fixnum
type-errors#error-positive-integer
type-errors#error-positive-number
type-errors#error-procedure
type-errors#error-rational
type-errors#error-real
type-errors#error-record
type-errors#error-record-type
type-errors#error-string
type-errors#error-structure
type-errors#error-symbol
type-errors#error-vector
type-errors#make-bad-argument-message
type-errors#make-error-type-message
type-errors#make-type-name-message
type-errors#signal-type-error
type-errors#warning-argument-type
u16vector
u16vector->blob
u16vector->blob/shared
u16vector->list
u16vector-length
u16vector-ref
u16vector-set!
u16vector?
u32vector
u32vector->blob
u32vector->blob/shared
u32vector->list
u32vector-length
u32vector-ref
u32vector-set!
u32vector?
u8vector
u8vector->blob
u8vector->blob/shared
u8vector->list
u8vector-length
u8vector-ref
u8vector-set!
u8vector?
ucs-range->char-set
ucs-range->char-set!
uncaught-exception-reason
uncaught-exception?
unfold
unfold-right
unicode-utils#ascii-codepoint?
unicode-utils#unicode-char->string
unicode-utils#unicode-make-string
unicode-utils#unicode-string
unicode-utils#unicode-surrogate?
unicode-utils#unicode-surrogates->codepoint
unless
unmap-file-from-memory
unregister-feature!
unsetenv
unzip1
unzip2
unzip3
unzip4
unzip5
use
user-information
utc-time->seconds
values
vector
vector->list
vector-copy!
vector-fill!
vector-length
vector-ref
vector-resize
vector-set!
vector?
void
warning
when
with-error-output-to-port
with-exception-handler
with-input-from-file
with-input-from-pipe
with-input-from-port
with-input-from-string
with-output-to-file
with-output-to-pipe
with-output-to-port
with-output-to-string
write
write-byte
write-char
write-line
write-string
write-u8vector
xcons
xsubstring
yes-or-no?
zero?
zip
